/**
 * This class is generated by jOOQ
 */
package com.songspk;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<com.songspk.tables.records.AlbumsRecord, java.lang.Long> IDENTITY_ALBUMS = Identities0.IDENTITY_ALBUMS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.songspk.tables.records.AlbumsRecord> ALBUMS_LINK_KEY = UniqueKeys0.ALBUMS_LINK_KEY;
	public static final org.jooq.UniqueKey<com.songspk.tables.records.AlbumsRecord> ALBUMS_PKEY = UniqueKeys0.ALBUMS_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<com.songspk.tables.records.AlbumsRecord, java.lang.Long> IDENTITY_ALBUMS = createIdentity(com.songspk.tables.Albums.ALBUMS, com.songspk.tables.Albums.ALBUMS.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.songspk.tables.records.AlbumsRecord> ALBUMS_LINK_KEY = createUniqueKey(com.songspk.tables.Albums.ALBUMS, com.songspk.tables.Albums.ALBUMS.LINK);
		public static final org.jooq.UniqueKey<com.songspk.tables.records.AlbumsRecord> ALBUMS_PKEY = createUniqueKey(com.songspk.tables.Albums.ALBUMS, com.songspk.tables.Albums.ALBUMS.ID);
	}
}
